# BungeeWeb Configuration File

# Server settings
server:
  port: 8080

# Logged items
log:
  chat: true
  command: true
  join: true
  quit: true
  kick: true
  serverchange: true
  namechange: true

# MySQL details
database:
  host: 127.0.0.1
  port: 3306
  user: bungeeweb
  pass: password
  db: bungeeweb
  prefix: bungeeweb_