# BungeeWeb Configuration File

# Server settings
server:

  # Port to run the server on
  port: 8080

  # Amount of time in milliseconds between status checks
  statscheck: 5000

# Logged items
log:
  chat: true
  command: true
  join: true
  quit: true
  kick: true
  serverchange: true

# Graphed items
stats:
  playercount: true
  maxplayers: true
  activity: true

# MySQL details
database:
  host: 127.0.0.1
  port: 3306
  user: bungeeweb
  pass: password
  db: bungeeweb
  prefix: bungeeweb_